// <auto-generated />
namespace MusicPortal.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class sumejja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sumejja));
        
        string IMigrationMetadata.Id
        {
            get { return "201601030058497_sumejja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
